# Generated by Django 3.2.10 on 2021-12-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_youtube_youtube', serialize=False, to='cms.cmsplugin'),
        ),
    ]
